name: ze2
base: core24
version: "2.0.0"
summary: ze2 is an MS-DOS inspired text editor
description: |
  ze2 pays homage to the classic MS-DOS Editor and PE2, but with a modern interface and input controls similar to VS Code. Learn more at https://github.com/microsoft/edit

  Disclaimer: This is an unofficial Snap and it is not endorsed by nor affiliated officially with Microsoft Corporation.

grade: stable
confinement: strict

apps:
  ze2:
    command: bin/ze2
    plugs:
      - home

parts:
  ze2:
    source: .
    source-type: git
    plugin: rust
    rust-path: crates/ze2
    build-packages:
      - build-essential
