.TH ZE2 1 "version 2.0.0"
.SH NAME
ze2 \- a simple text editor
.SH SYNOPSIS
\fBze2\fP [\fIOPTIONS\fP]... [\fIARGUMENTS\fP]...
.SH DESCRIPTION
ze2 is a simple text editor inspired by MS-DOS edit.
.SH EDITING
ze2 is an interactive mode-less editor. Use F10 to access the menus.
.SH ARGUMENTS
.TP
\fIFILE[:LINE[:COLUMN]]\fP
The file to open, optionally with line and column (e.g., \fBfoo.txt:123:45\fP).
.SH OPTIONS
.TP
\fB\-h\fP, \fB\-\-help\fP
Print the help message.
.TP
\fB\-v\fP, \fB\-\-version\fP
Print the version number.
.SH COPYRIGHT
Copyright \(co Microsoft Corporation.
.br
Licensed under the MIT License.
.SH SEE ALSO
.UR https://github.com/microsoft/edit
.UE
